/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:24a59afc-231b-4b30-9099-e1aa237b6b81",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_CbeTYuQR8",
    "aws_user_pools_web_client_id": "rr6hklg513i5lhriiodd735g4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dqqri5cqvjcofedjymxfk3wjvu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ckpoag3mubdrxk4vn6w6tem42u"
};


export default awsmobile;
